# Generated by Django 2.2.2 on 2019-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190801_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='itemsPaidFor',
        ),
    ]
