# Generated by Django 2.2.2 on 2019-08-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_buyer_itemspaidfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travellerUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
