# Generated by Django 2.0.1 on 2019-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190802_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuyer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
